name: animated_notch_bottom_bar
description: This package helps you to achieve animated notch bottom navigation bar with any widget as children.
version: 1.0.3
repository : https://github.com/Mindinventory/animated_notch_bottom_bar
issue_tracker: https://github.com/Mindinventory/animated_notch_bottom_bar/issues

environment:
  sdk: ">=3.2.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

